# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"
title: Michael Jörg
description: Software Developer, Architect and Requirements Guy
logo: assets/images/mijoe.jpeg
google_analytics: UA-132354283-1
